# Generated by Django 4.1.7 on 2023-03-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
    ]
