# Generated by Django 4.1.3 on 2022-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='bio',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, null=True, unique=True, verbose_name='Заголовок'),
        ),
    ]
