# Generated by Django 4.1.3 on 2022-11-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0008_postcomment_remove_todo_bio_remove_todo_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-created',), 'verbose_name': 'Комментарий к публикации', 'verbose_name_plural': 'Комментарии к публикациям'},
        ),
        migrations.AddField(
            model_name='postcomment',
            name='article',
            field=models.ForeignKey(blank=True, default=None, help_text='<small class="text-muted">ForeignKey</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.post', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='<small class="text-muted">DateTimeField</small><hr><br>', null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='text',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='<small class="text-muted">ForeignKey</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
