# Generated by Django 4.1.3 on 2022-11-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_delete_todocomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
    ]
