# Generated by Django 4.1.3 on 2022-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_alter_postcomment_options_remove_postcomment_article_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
