# Generated by Django 4.1.7 on 2023-03-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0016_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
