# Generated by Django 4.1.7 on 2023-03-08 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0017_delete_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Todo',
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-updated',), 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
