# Generated by Django 4.1.7 on 2023-03-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0019_rename_logmodel_logging_alter_logging_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logging',
        ),
    ]
